#!/bin/zsh
SCREENNAME=$1
VIEWMODELNAME=$2
SCREENFILENAME=$3
VIEWMODELFILENAME=$4
DIR=$5
VIEWMODELCONTENTPATH='./viewmodel_content.txt'
SCREENCONTENTPATH='./screen_content.txt'

/bin/mkdir -p $DIR

VIEWMODELPATH="$DIR/$VIEWMODELFILENAME.dart"
SCREENPATH="$DIR/$SCREENFILENAME.dart"
/usr/bin/touch $VIEWMODELPATH
VIEWMODELCONTENT=$(/bin/cat $VIEWMODELCONTENTPATH)
VIEWMODELCONTENT=$(/usr/bin/sed "s/\${VIEWMODELNAME}/$VIEWMODELNAME/g" <<< "$VIEWMODELCONTENT")
echo $VIEWMODELCONTENT > $VIEWMODELPATH

/usr/bin/touch $SCREENPATH
#/bin/cat $SCREENCONTENTPATH > $SCREENCONTENT
SCREENCONTENT=$(/bin/cat $SCREENCONTENTPATH)
SCREENCONTENT=$(/usr/bin/sed "s/\${SCREENNAME}/$SCREENNAME/g" <<< "$SCREENCONTENT")
SCREENCONTENT=$(/usr/bin/sed "s/\${VIEWMODELNAME}/$VIEWMODELNAME/g" <<< "$SCREENCONTENT")
SCREENCONTENT=$(/usr/bin/sed "s/\${SCREENFILENAME}/$SCREENFILENAME/g" <<< "$SCREENCONTENT")
SCREENCONTENT=$(/usr/bin/sed "s/\${VIEWMODELFILENAME}/$VIEWMODELFILENAME/g" <<< "$SCREENCONTENT")
echo $SCREENCONTENT > $SCREENPATH

